DROP TABLE IF EXISTS `GOODS`;

CREATE TABLE `GOODS` (
	`GOODS_ID`	varchar	NOT NULL,
	`CATEGORY_ID`	varchar	NOT NULL,
	`USER_ID`	varchar	NOT NULL,
	`GOODS_PRICE`	int	NULL,
	`INTR`	varchar	NULL,
	`IMG_URL`	varchar	NULL,
	`REGI_DT`	timestamp	NULL,
	`UPDA_DT`	timestamp	NULL
);

DROP TABLE IF EXISTS `GOODS_OPTION`;

CREATE TABLE `GOODS_OPTION` (
	`OPTION_ID`	varchar	NOT NULL,
	`GOODS_ID`	varchar	NOT NULL,
	`OPTION_NM`	varchar	NULL,
	`OPTION_PRICE`	int	NULL,
	`SORT`	int	NULL,
	`REGI_DT`	timestamp	NULL,
	`UPDA_DT`	timestamp	NULL
);

DROP TABLE IF EXISTS `CATEGORY`;

CREATE TABLE `CATEGORY` (
	`CATEGORY_ID`	varchar	NOT NULL,
	`CATEGORY_NM`	varchar	NULL,
	`REGI_ID`	varchar	NULL,
	`REGI_DT`	timestamp	NULL,
	`UPDA_ID`	varchar	NULL,
	`UPDA_DT`	timestamp	NULL
);

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`USER_ID`	varchar	NOT NULL,
	`NICK_NAME`	varchar	NULL,
	`NAME`	varchar	NULL,
	`ROLE`	varchar	NULL,
	`REGI_DT`	varchar	NULL
);

ALTER TABLE `GOODS` ADD CONSTRAINT `PK_GOODS` PRIMARY KEY (
	`GOODS_ID`
);

ALTER TABLE `GOODS_OPTION` ADD CONSTRAINT `PK_GOODS_OPTION` PRIMARY KEY (
	`OPTION_ID`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`CATEGORY_ID`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

