server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:h2:mem://localhost/~/test;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100  # rimit in size is 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always # logging coloring


# swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true